name: Package

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with maven
        run: mvn -B -Dmaven.javadoc.skip=true clean package -Dbuild.number=${{ github.run_number }} -Pshrink

      - name: Archive the server jar
        uses: actions/upload-artifact@v2
        with:
          name: Polus Server (jar)
          path: bootstrap/target/Polus.jar
